# Generated by Django 5.2.8 on 2025-11-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_remove_post_media_url_post_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="converted_at",
        ),
        migrations.AddField(
            model_name="post",
            name="visibility",
            field=models.CharField(
                choices=[("public", "Public"), ("private", "Friends Only")],
                default="public",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="media_type",
            field=models.CharField(
                choices=[("image", "Image"), ("video", "Video"), ("text", "Text")],
                default="image",
                max_length=10,
            ),
        ),
    ]
