# Generated by Django 5.2.8 on 2025-11-24 16:31

import posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_remove_post_converted_at_post_visibility_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=posts.models.qwip_file_name
            ),
        ),
    ]
