# Generated by Django 5.2.8 on 2026-01-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_comment_like"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
    ]
