# Generated by Django 5.2.8 on 2026-01-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0006_post_is_archived"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_flagged",
            field=models.BooleanField(default=False),
        ),
    ]
