# Generated by Django 5.2.8 on 2026-01-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_is_private"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="admin_notes",
            field=models.TextField(
                blank=True,
                help_text="Admin remarks regarding bans or warnings",
                null=True,
            ),
        ),
    ]
